# See http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml

spring:
    profiles:
        active: development
    freemarker:
        cache: false
    jpa:
        hibernate:
            ddl-auto: create
---

spring:
    profiles: development
    datasource:
        url: jdbc:hsqldb:file:/tmp/perculate.db
        username: sa
---
spring:
    profiles: production
    datasource:
        url: jdbc:hsqldb:mem:perculate
        username: sa
